package natsprojection;

import javafx.scene.text.Text;

public class Controller {
  public Text competitor1;
  public Text competitor2;
  public Text competitor3;
  public Text competitor4;
  public Text competitor5;
  public Text competitor6;
  public Text competitor7;
  public Text competitor8;
  public Text competitor9;
  public Text competitor10;
  public Text competitor11;
  public Text competitor12;
  public Text single1;
  public Text single2;
  public Text single3;
  public Text single4;
  public Text single5;
  public Text single6;
  public Text single7;
  public Text single8;
  public Text single9;
  public Text single10;
  public Text single11;
  public Text single12;
  public Text average1;
  public Text average2;
  public Text average3;
  public Text average4;
  public Text average5;
  public Text average6;
  public Text average7;
  public Text average8;
  public Text average9;
  public Text average10;
  public Text average11;
  public Text average12;
  Competitors competitors = new Competitors();
  public void setNames() {
    competitors.setPreConfig();
    competitor1.setText(competitors.name[0]);
    competitor2.setText(competitors.name[1]);
    competitor3.setText(competitors.name[2]);
    competitor4.setText(competitors.name[3]);
    competitor5.setText(competitors.name[4]);
    competitor6.setText(competitors.name[5]);
    competitor7.setText(competitors.name[6]);
    competitor8.setText(competitors.name[7]);
    competitor9.setText(competitors.name[8]);
    competitor10.setText(competitors.name[9]);
    competitor11.setText(competitors.name[10]);
    competitor12.setText(competitors.name[11]);
    single1.setText(competitors.pb_single[0]);
    single2.setText(competitors.pb_single[1]);
    single3.setText(competitors.pb_single[2]);
    single4.setText(competitors.pb_single[3]);
    single5.setText(competitors.pb_single[4]);
    single6.setText(competitors.pb_single[5]);
    single7.setText(competitors.pb_single[6]);
    single8.setText(competitors.pb_single[7]);
    single9.setText(competitors.pb_single[8]);
    single10.setText(competitors.pb_single[9]);
    single11.setText(competitors.pb_single[10]);
    single12.setText(competitors.pb_single[11]);
    average1.setText(competitors.pb_average[0]);
    average2.setText(competitors.pb_average[1]);
    average3.setText(competitors.pb_average[2]);
    average4.setText(competitors.pb_average[3]);
    average5.setText(competitors.pb_average[4]);
    average6.setText(competitors.pb_average[5]);
    average7.setText(competitors.pb_average[6]);
    average8.setText(competitors.pb_average[7]);
    average9.setText(competitors.pb_average[8]);
    average10.setText(competitors.pb_average[9]);
    average11.setText(competitors.pb_average[10]);
    average12.setText(competitors.pb_average[11]);
  }
}
